name: "Git Version Tagger"
description: "Bump and push git tag when triggered"
author: "Prospector"
inputs:
  github_token:
    description: "Required for permission to tag the repo."
    required: true
  version_type:
    description: "Which type of bump to use."
    required: true

runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "git-merge"
  color: "purple"
